import React,{useEffect,useMemo,useState} from 'react';
import {User} from 'firebase/auth';
import {collection,doc,getDoc,onSnapshot,query,orderBy} from 'firebase/firestore';
import {BarChart3,TrendingUp,Receipt,Users,Package,CalendarDays,CircleDollarSign} from 'lucide-react';
import {db} from './firebase';

type Invoice={amount?:number;status?:string;createdAt?:any;customerName?:string};
type Customer={id:string;name?:string;spent?:number};
type Product={type?:string;price?:number;stock?:number};
type Appointment={status?:string;date?:string;time?:string};
const money=(n:number)=>`₦${Math.round(n||0).toLocaleString()}`;
export default function Analytics({user}:{user:User}){const [invoices,setInvoices]=useState<Invoice[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[loading,setLoading]=useState(true);
useEffect(()=>{if(!db)return;let stops:(()=>void)[]=[];(async()=>{const s=await getDoc(doc(db,'users',user.uid));const bid=s.data()?.businessId;if(!bid){setLoading(false);return}const bind=(name:string,setter:any)=>{const ref=query(collection(db,'businesses',bid,name),orderBy('createdAt','desc'));return onSnapshot(ref,s=>{setter(s.docs.map(d=>d.data()));setLoading(false)},()=>setLoading(false))};const simple=(name:string,setter:any)=>onSnapshot(collection(db,'businesses',bid,name),s=>{setter(s.docs.map(d=>({id:d.id,...d.data()})));setLoading(false)},()=>setLoading(false));stops=[bind('invoices',setInvoices),simple('customers',setCustomers),simple('products',setProducts),simple('appointments',setAppointments)]})();return()=>stops.forEach(x=>x())},[user.uid]);
const stats=useMemo(()=>{const billed=invoices.reduce((n,x)=>n+Number(x.amount||0),0),collected=invoices.filter(x=>x.status==='Paid').reduce((n,x)=>n+Number(x.amount||0),0),outstanding=invoices.filter(x=>x.status==='Pending'||x.status==='Overdue').reduce((n,x)=>n+Number(x.amount||0),0),inventory=products.filter(x=>x.type==='Product').reduce((n,x)=>n+Number(x.price||0)*Number(x.stock||0),0);const paid=invoices.filter(x=>x.status==='Paid').length;const rate=invoices.length?Math.round(paid/invoices.length*100):0;return{billed,collected,outstanding,inventory,rate,paid,invoiceCount:invoices.length,customers:customers.length,appointments:appointments.length}},[invoices,customers,products,appointments]);
const monthly=useMemo(()=>{const now=new Date(),months=Array.from({length:6},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-5+i,1);return{key:`${d.getFullYear()}-${d.getMonth()}`,label:d.toLocaleString('en-US',{month:'short'})}});return months.map(m=>{const value=invoices.filter(x=>{const t=x.createdAt?.toDate?.()||new Date(x.createdAt||0);return `${t.getFullYear()}-${t.getMonth()}`===m.key&&x.status==='Paid'}).reduce((n,x)=>n+Number(x.amount||0),0);return{...m,value}})},[invoices]);
const max=Math.max(...monthly.map(x=>x.value),1);
return <section className="page analyticsPage"><div className="panelHead"><div><h3>Business analytics</h3><p>Live performance metrics calculated from your workspace data.</p></div></div><div className="analyticsCards"><div><span><CircleDollarSign size={17}/>Collected</span><strong>{money(stats.collected)}</strong><small>{stats.paid} paid invoice{stats.paid===1?'':'s'}</small></div><div><span><Receipt size={17}/>Outstanding</span><strong>{money(stats.outstanding)}</strong><small>{stats.invoiceCount} total invoices</small></div><div><span><Users size={17}/>Customers</span><strong>{stats.customers}</strong><small>Live customer records</small></div><div><span><Package size={17}/>Inventory value</span><strong>{money(stats.inventory)}</strong><small>Products at current stock</small></div></div><div className="analyticsGrid"><div className="panel"><div className="panelHead"><div><h3>Collected revenue</h3><p>Last 6 months</p></div></div><div className="analyticsChart">{monthly.map(x=><div className="analyticsBar" key={x.key}><div className="analyticsBarFill" style={{height:`${Math.max(4,x.value/max*100)}%`}} title={money(x.value)}/><small>{x.label}</small></div>)}</div></div><div className="panel"><div className="panelHead"><div><h3>Performance</h3><p>Current workspace health</p></div><BarChart3 size={20}/></div><div className="metricList"><div><span>Invoice collection rate</span><b>{stats.rate}%</b></div><div><span>Total billed</span><b>{money(stats.billed)}</b></div><div><span>Appointments</span><b>{stats.appointments}</b></div><div><span>Active products</span><b>{products.filter(x=>x.type==='Product'&&Number(x.stock||0)>0).length}</b></div></div></div></div>{loading&&<div className="analyticsLoading">Syncing live business data…</div>}</section>}
