import React,{useEffect,useMemo,useState} from 'react';
import {User} from 'firebase/auth';
import {addDoc,collection,deleteDoc,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,updateDoc} from 'firebase/firestore';
import {CalendarDays,Plus,Search,Edit3,Trash2,Save,X,Clock,UserRound,AlertCircle} from 'lucide-react';
import {db} from './firebase';

type Appointment={id:string;customerId:string;customerName:string;title:string;date:string;time:string;status:'Scheduled'|'Completed'|'Cancelled';notes:string};
type Customer={id:string;name:string};
const empty={customerId:'',title:'',date:'',time:'',status:'Scheduled' as Appointment['status'],notes:''};

export default function Appointments({user}:{user:User}){
 const [items,setItems]=useState<Appointment[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState<'All'|Appointment['status']>('All'),[show,setShow]=useState(false),[editing,setEditing]=useState<Appointment|null>(null),[loading,setLoading]=useState(true),[form,setForm]=useState(empty),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!db)return()=>{};let stop=()=>{};(async()=>{const s=await getDoc(doc(db,'users',user.uid));const bid=s.data()?.businessId;if(!bid){setLoading(false);return}stop=onSnapshot(query(collection(db,'businesses',bid,'appointments'),orderBy('date','asc')),x=>{setItems(x.docs.map(d=>({id:d.id,...d.data()} as Appointment)));setLoading(false)},()=>setLoading(false));const cstop=onSnapshot(query(collection(db,'businesses',bid,'customers'),orderBy('name','asc')),x=>setCustomers(x.docs.map(d=>({id:d.id,name:String(d.data().name||'')}))));return()=>cstop()})();return()=>stop()},[user.uid]);
 const filtered=useMemo(()=>items.filter(x=>(filter==='All'||x.status===filter)&&(`${x.customerName} ${x.title}`.toLowerCase().includes(q.toLowerCase()))),[items,q,filter]);
 const stats=useMemo(()=>({today:items.filter(x=>x.date===new Date().toISOString().slice(0,10)&&x.status!=='Cancelled').length,scheduled:items.filter(x=>x.status==='Scheduled').length,completed:items.filter(x=>x.status==='Completed').length}),[items]);
 function openNew(){setEditing(null);setForm({...empty,date:new Date().toISOString().slice(0,10)});setError('');setShow(true)}
 function openEdit(x:Appointment){setEditing(x);setForm({customerId:x.customerId||'',title:x.title||'',date:x.date||'',time:x.time||'',status:x.status||'Scheduled',notes:x.notes||''});setError('');setShow(true)}
 async function save(e:React.FormEvent){e.preventDefault();setError('');if(!form.customerId||!form.title.trim()||!form.date||!form.time){setError('Customer, appointment title, date and time are required.');return}if(!db)return;setBusy(true);try{const s=await getDoc(doc(db,'users',user.uid));const bid=s.data()?.businessId;if(!bid)throw Error('Business workspace not found.');const customer=customers.find(c=>c.id===form.customerId);const data={customerId:form.customerId,customerName:customer?.name||'Customer',title:form.title.trim(),date:form.date,time:form.time,status:form.status,notes:form.notes.trim(),updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'businesses',bid,'appointments',editing.id),data);else await addDoc(collection(db,'businesses',bid,'appointments'),{...data,createdAt:serverTimestamp()});setShow(false);setEditing(null)}catch(err:any){setError(err?.message||'Could not save appointment.')}finally{setBusy(false)}}
 async function remove(x:Appointment){if(!db||!confirm(`Delete ${x.title} for ${x.customerName}?`))return;const s=await getDoc(doc(db,'users',user.uid));const bid=s.data()?.businessId;if(bid)await deleteDoc(doc(db,'businesses',bid,'appointments',x.id))}
 return <section className="panel page appointmentsPage"><div className="panelHead"><div><h3>Appointments</h3><p>Schedule customer work and keep the team aligned.</p></div><button className="primary" onClick={openNew}><Plus size={17}/>New appointment</button></div><div className="appointmentStats"><div><span><CalendarDays size={16}/>Today</span><strong>{stats.today}</strong></div><div><span><Clock size={16}/>Scheduled</span><strong>{stats.scheduled}</strong></div><div><span><UserRound size={16}/>Completed</span><strong>{stats.completed}</strong></div></div><div className="productToolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search appointments..."/></div><div className="filters">{(['All','Scheduled','Completed','Cancelled'] as const).map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="tableWrap"><table><thead><tr><th>Appointment</th><th>Customer</th><th>Date</th><th>Time</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><div className="itemCell"><div className="itemIcon"><CalendarDays size={15}/></div><div><b>{x.title}</b>{x.notes&&<small>{x.notes}</small>}</div></div></td><td>{x.customerName}</td><td>{new Date(`${x.date}T00:00:00`).toLocaleDateString()}</td><td>{x.time}</td><td><span className={`tag ${x.status==='Cancelled'?'low':''}`}>{x.status}</span></td><td><div className="rowActions"><button title="Edit" onClick={()=>openEdit(x)}><Edit3 size={15}/></button><button title="Delete" onClick={()=>remove(x)}><Trash2 size={15}/></button></div></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={6}><div className="tableEmpty"><AlertCircle size={20}/><b>{items.length?'No matching appointments':'No appointments yet'}</b><span>{items.length?'Try another search or status filter.':'Schedule your first customer appointment.'}</span><button className="primary" onClick={openNew}><Plus size={15}/>New appointment</button></div></td></tr>}{loading&&<tr><td colSpan={6}><div className="tableEmpty"><span>Loading appointments…</span></div></td></tr>}</tbody></table></div>{show&&<AppointmentModal initial={editing} form={form} setForm={setForm} customers={customers} error={error} busy={busy} onClose={()=>{setShow(false);setEditing(null)}} onSave={save}/>}</section>
}
function AppointmentModal({initial,form,setForm,customers,error,busy,onClose,onSave}:{initial:Appointment|null;form:typeof empty;setForm:React.Dispatch<React.SetStateAction<typeof empty>>;customers:Customer[];error:string;busy:boolean;onClose:()=>void;onSave:(e:React.FormEvent)=>Promise<void>}){return <div className="modal"><form className="modalCard" onSubmit={onSave}><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow">SCHEDULE RECORD</span><h2>{initial?'Edit appointment':'New appointment'}</h2><p>Schedule work against a real customer in this workspace.</p><label>Customer<select value={form.customerId} onChange={e=>setForm(f=>({...f,customerId:e.target.value}))}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Appointment title<input autoFocus value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="e.g. Project review"/></label><div className="formGrid"><label>Date<input type="date" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))}/></label><label>Time<input type="time" value={form.time} onChange={e=>setForm(f=>({...f,time:e.target.value}))}/></label></div><label>Status<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value as Appointment['status']}))}><option>Scheduled</option><option>Completed</option><option>Cancelled</option></select></label><label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Optional notes"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':<><Save size={16}/>{initial?'Save changes':'Create appointment'}</>}</button></form></div>}
