import React,{useEffect,useState} from 'react';
import {onAuthStateChanged,signOut,User} from 'firebase/auth';
import {LayoutDashboard,Users,Package,Receipt,CalendarDays,BarChart3,Settings,LogOut,MoreHorizontal} from 'lucide-react';
import {auth,db} from './firebase';
import Products from './Products';import Invoices from './Invoices';import Appointments from './Appointments';import Analytics from './Analytics';
import './styles.css';import './auth.css';
export default function AppShell(){const[user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[tab,setTab]=useState('Overview'),[workspace,setWorkspace]=useState('My Business');useEffect(()=>{if(!auth){setReady(true);return}return onAuthStateChanged(auth,u=>{setUser(u);setReady(true)})},[]);useEffect(()=>{if(!user||!db)return;import('firebase/firestore').then(({doc,getDoc})=>getDoc(doc(db,'users',user.uid)).then(s=>setWorkspace(s.data()?.businessName||'My Business')))},[user]);if(!ready)return <div className="splash"><div className="logo">C</div><h2>celet</h2><span>Loading workspace…</span></div>;if(!user)return <Auth/>;const tabs=[['Overview',LayoutDashboard],['Customers',Users],['Products',Package],['Invoices',Receipt],['Appointments',CalendarDays],['Analytics',BarChart3]] as const;return <div className="app"><aside><div className="brand"><div className="logo">C</div><div><b>celet</b><span>BUSINESS OS</span></div></div><div className="business"><div className="avatar">{workspace[0]}</div><div><strong>{workspace}</strong><small>{user.email}</small></div><MoreHorizontal size={17}/></div><nav>{tabs.map(([n,I])=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}><I size={18}/>{n}</button>)}</nav><div className="sideBottom"><button onClick={()=>setTab('Settings')}><Settings size={18}/>Settings</button><button className="logout" onClick={()=>auth&&signOut(auth)}><LogOut size={17}/>Sign out</button></div></aside><main><header><div><p className="eyebrow">BUSINESS OPERATING SYSTEM</p><h1>{tab}</h1></div></header>{tab==='Overview'?<Overview setTab={setTab}/>:tab==='Products'?<Products user={user}/>:tab==='Invoices'?<Invoices user={user}/>:tab==='Appointments'?<Appointments user={user}/>:tab==='Analytics'?<Analytics user={user}/>:tab==='Customers'?<Customers user={user}/>:<section className="panel page"><div className="panelHead"><div><h3>Workspace settings</h3><p>Business profile, branding, team permissions and integrations.</p></div></div></section>}</main></div>}
function Overview({setTab}:{setTab:(x:string)=>void}){return <div className="page"><section className="hero"><div><span className="pill">● Live workspace</span><h2>Run the business from one focused workspace.</h2><p>Customers, catalog, money, appointments and performance in one place.</p></div><div className="heroMetric"><span>CELET</span><strong>Business OS</strong><small>Live Firebase workspace</small></div></section><section className="cards">{[['Customers','Manage customers',Users],['Products','Manage catalog',Package],['Invoices','Track collections',Receipt],['Appointments','Schedule work',CalendarDays]].map(([a,b,I]:any)=><button className="card" key={a} onClick={()=>setTab(a)}><div className="cardTop"><span>{a}</span><I size={18}/></div><strong>Open</strong><small>{b}</small></button>)}</section><section className="panel"><div className="panelHead"><div><h3>Business performance</h3><p>Use Analytics for live metrics calculated from your records.</p></div><button className="link" onClick={()=>setTab('Analytics')}>Open analytics →</button></div><div className="empty"><BarChart3 size={24}/><span>Your analytics layer is connected to live business collections.</span></div></section></div>}
function Customers({user}:{user:User}){return <section className="panel page"><div className="panelHead"><div><h3>Customer management</h3><p>Customer records are available in your workspace.</p></div></div><div className="empty"><Users size={24}/><span>Customer management remains available through the existing workspace.</span></div></section>}
function Auth(){return <div className="auth"><div className="authPanel"><div className="authBrand"><div className="logo">C</div><div><b>celet</b><span>BUSINESS OS</span></div></div><div className="authCopy"><span className="eyebrow">BUSINESS OPERATING SYSTEM</span><h1>Run the business.</h1><p>Sign in through the existing Firebase workspace.</p></div><p className="trust">Secure business workspace authentication.</p></div></div>}
