import React,{useEffect,useMemo,useState} from 'react';
import {User} from 'firebase/auth';
import {addDoc,collection,deleteDoc,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,updateDoc} from 'firebase/firestore';
import {Receipt,Plus,Search,Edit3,Trash2,X,Save,CheckCircle2,CircleDollarSign,Clock3} from 'lucide-react';
import {db} from './firebase';

type Invoice={id:string;number:string;customerId:string;customerName:string;items:string;amount:number;status:'Draft'|'Pending'|'Paid'|'Overdue';dueDate:string;notes:string;paidAt?:unknown};
const blank={customerName:'',items:'',amount:'',status:'Pending' as Invoice['status'],dueDate:'',notes:''};
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`;
export default function Invoices({user}:{user:User}){const [items,setItems]=useState<Invoice[]>([]),[customers,setCustomers]=useState<any[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('All'),[show,setShow]=useState(false),[editing,setEditing]=useState<Invoice|null>(null),[form,setForm]=useState(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let a=()=>{},b=()=>{};if(!db)return;getDoc(doc(db,'users',user.uid)).then(s=>{const bid=s.data()?.businessId;if(!bid){setLoading(false);return}a=onSnapshot(query(collection(db,'businesses',bid,'invoices'),orderBy('createdAt','desc')),s=>{setItems(s.docs.map(d=>({id:d.id,...d.data()} as Invoice)));setLoading(false)},()=>setLoading(false));b=onSnapshot(collection(db,'businesses',bid,'customers'),s=>setCustomers(s.docs.map(d=>({id:d.id,...d.data()}))))});return()=>{a();b()}},[user.uid]);
 const filtered=useMemo(()=>items.filter(x=>(filter==='All'||x.status===filter)&&((x.number||'').toLowerCase().includes(q.toLowerCase())||(x.customerName||'').toLowerCase().includes(q.toLowerCase())||(x.items||'').toLowerCase().includes(q.toLowerCase()))),[items,q,filter]);
 const stats=useMemo(()=>({total:items.reduce((n,x)=>n+Number(x.amount||0),0),paid:items.filter(x=>x.status==='Paid').reduce((n,x)=>n+Number(x.amount||0),0),pending:items.filter(x=>x.status==='Pending'||x.status==='Overdue').reduce((n,x)=>n+Number(x.amount||0),0),count:items.length}),[items]);
 function openNew(){setEditing(null);setForm(blank);setError('');setShow(true)} function edit(x:Invoice){setEditing(x);setForm({customerName:x.customerName||'',items:x.items||'',amount:String(x.amount||''),status:x.status,dueDate:x.dueDate||'',notes:x.notes||''});setError('');setShow(true)}
 async function save(e:React.FormEvent){e.preventDefault();const amount=Number(form.amount||0);if(!form.customerName.trim()||!form.items.trim()){setError('Customer and item/service are required.');return}if(amount<=0||Number.isNaN(amount)){setError('Enter a valid invoice amount.');return}if(!db)return;setBusy(true);try{const s=await getDoc(doc(db,'users',user.uid)),bid=s.data()?.businessId;if(!bid)throw Error('Business workspace not found.');const data={customerName:form.customerName.trim(),items:form.items.trim(),amount,status:form.status,dueDate:form.dueDate,notes:form.notes.trim(),updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'businesses',bid,'invoices',editing.id),data);else{const count=items.length+1;await addDoc(collection(db,'businesses',bid,'invoices'),{...data,number:`INV-${String(count).padStart(4,'0')}`,createdAt:serverTimestamp()})}setShow(false)}catch(err:any){setError(err.message||'Could not save invoice.')}finally{setBusy(false)}}
 async function markPaid(x:Invoice){if(!db)return;const s=await getDoc(doc(db,'users',user.uid)),bid=s.data()?.businessId;if(bid)await updateDoc(doc(db,'businesses',bid,'invoices',x.id),{status:'Paid',paidAt:serverTimestamp(),updatedAt:serverTimestamp()})}
 async function remove(x:Invoice){if(!db||!confirm(`Delete ${x.number}? This cannot be undone.`))return;const s=await getDoc(doc(db,'users',user.uid)),bid=s.data()?.businessId;if(bid)await deleteDoc(doc(db,'businesses',bid,'invoices',x.id))}
 return <section className="panel page invoicesPage"><div className="panelHead"><div><h3>Invoices & payments</h3><p>Create invoices, track collections and keep cash flow visible.</p></div><button className="primary" onClick={openNew}><Plus size={17}/>Create invoice</button></div><div className="invoiceStats"><div><span><Receipt size={16}/>Invoices</span><strong>{stats.count}</strong></div><div><span><CircleDollarSign size={16}/>Billed</span><strong>{money(stats.total)}</strong></div><div><span><CheckCircle2 size={16}/>Collected</span><strong>{money(stats.paid)}</strong></div><div><span><Clock3 size={16}/>Outstanding</span><strong>{money(stats.pending)}</strong></div></div><div className="productToolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoices or customers..."/></div><div className="filters">{['All','Draft','Pending','Paid','Overdue'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="tableWrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Description</th><th>Amount</th><th>Status</th><th>Due</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.number}</b></td><td>{x.customerName}</td><td>{x.items}</td><td>{money(x.amount)}</td><td><span className={`tag invoice-${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x.dueDate||'—'}</td><td><div className="rowActions">{x.status!=='Paid'&&<button title="Mark paid" onClick={()=>markPaid(x)}><CheckCircle2 size={15}/></button>}<button title="Edit" onClick={()=>edit(x)}><Edit3 size={15}/></button><button title="Delete" onClick={()=>remove(x)}><Trash2 size={15}/></button></div></td></tr>)}{loading&&<tr><td colSpan={7}><div className="tableEmpty"><span>Loading invoices…</span></div></td></tr>}{!loading&&!filtered.length&&<tr><td colSpan={7}><div className="tableEmpty"><Receipt size={20}/><b>{items.length?'No matching invoices':'No invoices yet'}</b><span>Create your first invoice to start tracking revenue.</span><button className="primary" onClick={openNew}><Plus size={15}/>Create invoice</button></div></td></tr>}</tbody></table></div>{show&&<InvoiceModal form={form} setForm={setForm} customers={customers} initial={editing} error={error} busy={busy} onClose={()=>setShow(false)} onSave={save}/>}</section>}
function InvoiceModal({form,setForm,customers,initial,error,busy,onClose,onSave}:{form:typeof blank;setForm:React.Dispatch<React.SetStateAction<typeof blank>>;customers:any[];initial:Invoice|null;error:string;busy:boolean;onClose:()=>void;onSave:(e:React.FormEvent)=>Promise<void>}){return <div className="modal"><form className="modalCard" onSubmit={onSave}><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow">FINANCIAL RECORD</span><h2>{initial?'Edit invoice':'Create invoice'}</h2><p>Issue a bill and track its payment status.</p><label>Customer<select value={form.customerName} onChange={e=>setForm(f=>({...f,customerName:e.target.value}))}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><label>Product or service<input value={form.items} onChange={e=>setForm(f=>({...f,items:e.target.value}))} placeholder="e.g. Business website"/></label><div className="formGrid"><label>Amount (₦)<input type="number" min="1" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))} placeholder="0"/></label><label>Status<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value as Invoice['status']}))}>{['Draft','Pending','Paid','Overdue'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm(f=>({...f,dueDate:e.target.value}))}/></label><label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Optional payment notes"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':<><Save size={16}/>{initial?'Save changes':'Create invoice'}</>}</button></form></div>}
