import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,User} from 'firebase/auth';
import {addDoc,collection,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,setDoc} from 'firebase/firestore';
import {LayoutDashboard,Users,Package,Receipt,CalendarDays,BarChart3,Settings,MessageCircle,Plus,Search,MoreHorizontal,ArrowUpRight,TrendingUp,WalletCards,CheckCircle2,LogOut,X,ShieldCheck} from 'lucide-react';
import {auth,db} from './firebase';
import './styles.css';import './auth.css';

type Customer={id:string,name:string,phone:string,status:string,spent:number};
const demoCustomers:Customer[]=[{id:'1',name:'Amara Okafor',phone:'+234 803 112 9081',status:'Active',spent:185000},{id:'2',name:'Daniel James',phone:'+234 806 442 1187',status:'Active',spent:92000},{id:'3',name:'Blessing Umeh',phone:'+234 810 234 7762',status:'New',spent:48000},{id:'4',name:'Kelechi Obi',phone:'+234 701 882 4401',status:'Active',spent:310000}];
const demoSales=[['INV-1048','Amara Okafor','Website package','₦180,000','Paid'],['INV-1047','Daniel James','Business branding','₦95,000','Paid'],['INV-1046','Blessing Umeh','Starter website','₦48,000','Pending'],['INV-1045','Kelechi Obi','E-commerce build','₦310,000','Paid']];
const tabs=[['Overview',LayoutDashboard],['Customers',Users],['Products',Package],['Invoices',Receipt],['Appointments',CalendarDays],['Analytics',BarChart3]] as const;
function App(){const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[tab,setTab]=useState('Overview'),[q,setQ]=useState(''),[show,setShow]=useState(false),[customers,setCustomers]=useState(demoCustomers),[workspace,setWorkspace]=useState('My Business');
useEffect(()=>{if(!auth){setReady(true);return}return onAuthStateChanged(auth,u=>{setUser(u);setReady(true)})},[]);
useEffect(()=>{if(!user||!db)return;let stop=()=>{};getDoc(doc(db,'users',user.uid)).then(s=>{const d=s.data();if(d?.businessId){setWorkspace(d.businessName||'My Business');stop=onSnapshot(query(collection(db,'businesses',d.businessId,'customers'),orderBy('createdAt','desc')),x=>setCustomers(x.docs.map(v=>({id:v.id,...v.data()} as Customer))))}});return()=>stop()},[user]);
const filtered=useMemo(()=>customers.filter(c=>(c.name||'').toLowerCase().includes(q.toLowerCase())||(c.phone||'').includes(q)),[customers,q]);
if(!ready)return <div className="splash"><div className="logo">C</div><h2>celet</h2><span>Loading workspace…</span></div>;if(!user)return <AuthScreen/>;
async function createRecord(){setShow(false);if(!db)return;const s=await getDoc(doc(db,'users',user.uid)),businessId=s.data()?.businessId;if(!businessId)return;await addDoc(collection(db,'businesses',businessId,'customers'),{name:'New customer',phone:'+234 800 000 0000',status:'New',spent:0,createdAt:serverTimestamp()})}
return <div className="app"><aside><div className="brand"><div className="logo">C</div><div><b>celet</b><span>BUSINESS OS</span></div></div><div className="business"><div className="avatar">{workspace[0]}</div><div><strong>{workspace}</strong><small>{user.email}</small></div><MoreHorizontal size={17}/></div><nav>{tabs.map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I size={18}/>{n}</button>)}</nav><div className="sideBottom"><button onClick={()=>setTab('Settings')}><Settings size={18}/>Settings</button><div className="upgrade"><b>Celet Pro</b><p>Team controls, automation and advanced reports.</p><button>Explore Pro <ArrowUpRight size={14}/></button></div><button className="logout" onClick={()=>signOut(auth!)}><LogOut size={17}/>Sign out</button></div></aside><main><header><div><p className="eyebrow">THURSDAY, SEPTEMBER 10, 2026</p><h1>{tab}</h1></div><div className="actions"><button className="icon"><MessageCircle size={18}/></button><button className="primary" onClick={()=>setShow(true)}><Plus size={18}/>New transaction</button><div className="profile">{(user.email||'U')[0].toUpperCase()}</div></div></header>{tab==='Overview'?<Overview onInvoices={()=>setTab('Invoices')}/>:tab==='Customers'?<Customers data={filtered} q={q} setQ={setQ} onAdd={()=>setShow(true)}/>:<section className="panel page"><div className="panelHead"><div><h3>{tab} management</h3><p>Operate your {tab.toLowerCase()} from one workspace.</p></div><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/>Add record</button></div><div className="empty"><div className="emptyIcon"><Ico tab={tab}/></div><h2>{tab} are ready for real data</h2><p>Celet has the workspace architecture ready. Create your first record to begin building your operating history.</p><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/>Create record</button></div></section>}{show&&<div className="modal"><div className="modalCard"><button className="close" onClick={()=>setShow(false)}><X/></button><span className="eyebrow">QUICK ACTION</span><h2>New customer</h2><p>Create a real Firestore record in the current business workspace.</p><input placeholder="Customer name"/><input placeholder="Phone number"/><button className="primary full" onClick={createRecord}>Save customer</button></div></div>}</main></div>}
function Overview({onInvoices}:{onInvoices:()=>void}){return <><section className="hero"><div><span className="pill">● Business is healthy</span><h2>Good evening, your business is moving.</h2><p>One operating system for customers, money and day-to-day work.</p></div><div className="heroMetric"><span>MONTHLY REVENUE</span><strong>₦633,000</strong><small><TrendingUp size={14}/> 18.4% vs last month</small></div></section><section className="cards">{[['Revenue','₦633,000','18.4%',WalletCards],['Customers','1,248','12.8%',Users],['Invoices','₦481,000','9.2%',Receipt],['Appointments','34','16.1%',CalendarDays]].map(([a,b,c,I]:any)=><div className="card" key={a}><div className="cardTop"><span>{a}</span><I size={18}/></div><strong>{b}</strong><small><TrendingUp size={13}/> {c} this month</small></div>)}</section><section className="grid"><div className="panel"><div className="panelHead"><div><h3>Revenue overview</h3><p>Last 6 months</p></div><select><option>2026</option></select></div><div className="chart"><div className="bars">{[42,58,48,72,63,88].map((h,i)=><div className="barWrap" key={i}><div className="bar" style={{height:h+'%'}}/><small>{['Apr','May','Jun','Jul','Aug','Sep'][i]}</small></div>)}</div></div></div><div className="panel activity"><div className="panelHead"><div><h3>Recent activity</h3><p>Latest business events</p></div></div>{[['Invoice paid','Amara Okafor paid INV-1048','₦180,000'],['New customer','Blessing Umeh joined your business','Today'],['Appointment','Project review scheduled','Tomorrow']].map(x=><div className="activityRow" key={x[0]}><div className="activityIcon"><CheckCircle2 size={16}/></div><div><b>{x[0]}</b><p>{x[1]}</p></div><strong>{x[2]}</strong></div>)}</div></section><section className="panel"><div className="panelHead"><div><h3>Recent transactions</h3><p>Latest invoices and payments</p></div><button className="link" onClick={onInvoices}>View invoices</button></div><table><thead><tr><th>Invoice</th><th>Customer</th><th>Item</th><th>Amount</th><th>Status</th></tr></thead><tbody>{demoSales.map(s=><tr key={s[0]}>{s.map((v,i)=><td key={i} className={i===4?(v==='Paid'?'paid':'pending'):''}>{v}</td>)}</tr>)}</tbody></table></section></>}
function Customers({data,q,setQ,onAdd}:{data:Customer[];q:string;setQ:(v:string)=>void;onAdd:()=>void}){return <section className="panel page"><div className="panelHead"><div><h3>Customer management</h3><p>Search, understand and grow your customer base.</p></div><button className="primary" onClick={onAdd}><Plus size={17}/>Add customer</button></div><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers..."/></div><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Status</th><th>Total spend</th><th/></tr></thead><tbody>{data.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.phone}</td><td><span className="tag">{c.status}</span></td><td>₦{Number(c.spent||0).toLocaleString()}</td><td><button className="dots"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></section>}
function AuthScreen(){const [mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[business,setBusiness]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{if(!auth||!db)throw new Error('Firebase is not configured. Add the VITE_FIREBASE_* values in Netlify environment variables.');if(mode==='login')await signInWithEmailAndPassword(auth,email,password);else{const c=await createUserWithEmailAndPassword(auth,email,password),id=c.user.uid,name=business||'My Business';await setDoc(doc(db,'users',id),{businessId:id,businessName:name,role:'owner',email});await setDoc(doc(db,'businesses',id),{name,ownerId:id,currency:'NGN',createdAt:serverTimestamp()})}}catch(err:any){setError(err?.message?.replace('Firebase: ','')||'Unable to continue.')}finally{setBusy(false)}}return <div className="auth"><div className="authPanel"><div className="authBrand"><div className="logo">C</div><div><b>celet</b><span>BUSINESS OS</span></div></div><div className="authCopy"><span className="eyebrow">BUSINESS OPERATING SYSTEM</span><h1>{mode==='login'?'Run the business.':'Build your workspace.'}</h1><p>{mode==='login'?'Everything important in one calm, focused workspace.':'Create a secure workspace for customers, sales and operations.'}</p></div><form onSubmit={submit}>{mode==='signup'&&<label>Business name<input value={business} onChange={e=>setBusiness(e.target.value)} placeholder="e.g. LOOM Studio" required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@business.com" required/></label><label>Password<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" required/></label>{error&&<div className="error">{error}</div>}<button className="primary authButton" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create workspace'}</button></form><button className="switch" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'New to Celet? Create a workspace':'Already have an account? Sign in'}</button><div className="trust"><ShieldCheck size={15}/> Your workspace is isolated by business account.</div></div><div className="authVisual"><div className="visualCard"><div className="visualTop"><span>CELET / CONTROL</span><span>LIVE</span></div><div className="visualRevenue">₦633,000<small>Monthly revenue</small></div><div className="visualLine">{[35,50,42,67,58,82].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="visualStats"><span>1,248 customers</span><span>34 appointments</span></div></div></div></div>}
function Ico({tab}:{tab:string}){return tab==='Customers'?<Users/>:tab==='Products'?<Package/>:tab==='Invoices'?<Receipt/>:tab==='Appointments'?<CalendarDays/>:tab==='Settings'?<Settings/>:<BarChart3/>}
createRoot(document.getElementById('root')!).render(<App/>);
