import React,{useEffect,useMemo,useState} from 'react';
import {User} from 'firebase/auth';
import {addDoc,collection,deleteDoc,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,updateDoc} from 'firebase/firestore';
import {Package,Plus,Search,Edit3,Trash2,Save,X,Boxes,Tag,AlertCircle} from 'lucide-react';
import {db} from './firebase';

type Product={id:string;name:string;type:'Product'|'Service';category:string;price:number;stock:number;status:string;description:string};

const emptyForm={name:'',type:'Product' as Product['type'],category:'',price:'',stock:'',description:''};

export default function Products({user}:{user:User}){
 const [items,setItems]=useState<Product[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState<'All'|'Product'|'Service'>('All'),[show,setShow]=useState(false),[editing,setEditing]=useState<Product|null>(null),[loading,setLoading]=useState(true);
 const [form,setForm]=useState(emptyForm),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let stop=()=>{}; if(!db)return()=>{}; (async()=>{const snap=await getDoc(doc(db,'users',user.uid));const businessId=snap.data()?.businessId;if(!businessId){setLoading(false);return}stop=onSnapshot(query(collection(db,'businesses',businessId,'products'),orderBy('createdAt','desc')),s=>{setItems(s.docs.map(d=>({id:d.id,...d.data()} as Product)));setLoading(false)},()=>setLoading(false))})();return()=>stop()},[user.uid]);
 const filtered=useMemo(()=>items.filter(x=>(filter==='All'||x.type===filter)&&((x.name||'').toLowerCase().includes(q.toLowerCase())||(x.category||'').toLowerCase().includes(q.toLowerCase()))),[items,q,filter]);
 const stats=useMemo(()=>({products:items.filter(x=>x.type==='Product').length,services:items.filter(x=>x.type==='Service').length,stock:items.filter(x=>x.type==='Product').reduce((n,x)=>n+Number(x.stock||0),0),value:items.filter(x=>x.type==='Product').reduce((n,x)=>n+(Number(x.price||0)*Number(x.stock||0)),0)}),[items]);
 function openNew(){setEditing(null);setForm(emptyForm);setError('');setShow(true)}
 function openEdit(item:Product){setEditing(item);setForm({name:item.name||'',type:item.type||'Product',category:item.category||'',price:String(item.price??''),stock:String(item.stock??''),description:item.description||''});setError('');setShow(true)}
 async function save(e:React.FormEvent){e.preventDefault();setError('');const price=Number(form.price||0),stock=Number(form.stock||0);if(!form.name.trim()){setError('Name is required.');return}if(price<0||Number.isNaN(price)){setError('Enter a valid price.');return}if(stock<0||Number.isNaN(stock)){setError('Stock cannot be negative.');return}if(!db)return;setBusy(true);try{const snap=await getDoc(doc(db,'users',user.uid));const businessId=snap.data()?.businessId;if(!businessId)throw new Error('Business workspace not found.');const data={name:form.name.trim(),type:form.type,category:form.category.trim(),price,stock:form.type==='Product'?stock:0,description:form.description.trim(),updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'businesses',businessId,'products',editing.id),data);else await addDoc(collection(db,'businesses',businessId,'products'),{...data,createdAt:serverTimestamp()});setShow(false);setEditing(null)}catch(err:any){setError(err?.message||'Could not save this record.')}finally{setBusy(false)}}
 async function remove(item:Product){if(!db||!confirm(`Delete ${item.name}? This cannot be undone.`))return;const snap=await getDoc(doc(db,'users',user.uid));const businessId=snap.data()?.businessId;if(businessId)await deleteDoc(doc(db,'businesses',businessId,'products',item.id))}
 return <section className="panel page productsPage"><div className="panelHead"><div><h3>Products & services</h3><p>Manage what you sell, your pricing and available stock.</p></div><button className="primary" onClick={openNew}><Plus size={17}/>Add item</button></div><div className="productStats"><div><span><Package size={16}/>Products</span><strong>{stats.products}</strong></div><div><span><Tag size={16}/>Services</span><strong>{stats.services}</strong></div><div><span><Boxes size={16}/>Units in stock</span><strong>{stats.stock.toLocaleString()}</strong></div><div><span>Inventory value</span><strong>₦{stats.value.toLocaleString()}</strong></div></div><div className="productToolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products and services..."/></div><div className="filters">{(['All','Product','Service'] as const).map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x==='Product'?'Products':x==='Service'?'Services':x}</button>)}</div></div><div className="tableWrap"><table><thead><tr><th>Item</th><th>Type</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><div className="itemCell"><div className="itemIcon"><Package size={15}/></div><div><b>{x.name}</b>{x.description&&<small>{x.description}</small>}</div></div></td><td>{x.type}</td><td>{x.category||'—'}</td><td>₦{Number(x.price||0).toLocaleString()}</td><td>{x.type==='Product'?Number(x.stock||0).toLocaleString():'—'}</td><td><span className={`tag ${x.type==='Product'&&Number(x.stock||0)===0?'low':''}`}>{x.type==='Service'?'Available':Number(x.stock||0)>0?'In stock':'Out of stock'}</span></td><td><div className="rowActions"><button title="Edit" onClick={()=>openEdit(x)}><Edit3 size={15}/></button><button title="Delete" onClick={()=>remove(x)}><Trash2 size={15}/></button></div></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={7}><div className="tableEmpty"><AlertCircle size={20}/><b>{items.length?'No matching items':'Your catalog is empty'}</b><span>{items.length?'Try another search or filter.':'Add your first product or service to start building your catalog.'}</span><button className="primary" onClick={openNew}><Plus size={15}/>Add item</button></div></td></tr>}{loading&&<tr><td colSpan={7}><div className="tableEmpty"><span>Loading catalog…</span></div></td></tr>}</tbody></table></div>{show&&<ProductModal initial={editing} form={form} setForm={setForm} error={error} busy={busy} onClose={()=>{setShow(false);setEditing(null)}} onSave={save}/>}</section>
}

function ProductModal({initial,form,setForm,error,busy,onClose,onSave}:{initial:Product|null;form:typeof emptyForm;setForm:React.Dispatch<React.SetStateAction<typeof emptyForm>>;error:string;busy:boolean;onClose:()=>void;onSave:(e:React.FormEvent)=>Promise<void>}){return <div className="modal"><form className="modalCard" onSubmit={onSave}><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow">CATALOG RECORD</span><h2>{initial?'Edit item':'New product or service'}</h2><p>Keep pricing and availability accurate for your business.</p><div className="formGrid"><label>Name<input autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="e.g. Business Website"/></label><label>Type<select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value as Product['type']}))}><option>Product</option><option>Service</option></select></label></div><div className="formGrid"><label>Category<input value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))} placeholder="e.g. Websites"/></label><label>Price (₦)<input type="number" min="0" value={form.price} onChange={e=>setForm(f=>({...f,price:e.target.value}))} placeholder="0"/></label></div><label>Stock units{form.type==='Service'?<div className="disabledField">Services don't require stock tracking</div>:<input type="number" min="0" value={form.stock} onChange={e=>setForm(f=>({...f,stock:e.target.value}))} placeholder="0"/>}</label><label>Description<textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} placeholder="Short description of this item" rows={3}/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':<><Save size={16}/>{initial?'Save changes':'Create item'}</>}</button></form></div>}
